apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.15.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
  transport:
    service:
      metadata:
        labels:
          my-custom: label
      spec:
        type: NodePort
