apiVersion: v1
kind: Service
metadata:
  annotations:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: NodePort
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  ports:
    - name: http
      nodePort: 30950
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      nodePort: 30050
      port: 443
      protocol: TCP
      targetPort: https
      appProtocol: https
  selector:
    app: ingress-nginx